### ISSUE TITLE
V jakých případech může dojít k `RuntimeError`u při načítání GeoJSONu?

### ISSUE THREAD

**Issue by xtompok** [nekola03/du3#1]
Každá odchycená výjimka by měla mít uvedenu chybovou hlášku, reakci v programu nebo alespoň komentář, proč je tam `pass` a nic se s výjimkou nedělá

**Comment by nekola03** [comment]
Opraveno. Jenom jsem se chtěl zeptat. V jednom dotazu stackOverFlow j napsáno, že RuntimeError je taky možnou, né moc častou chybou programu. Nevíš, co přesně vlastně znamená. Našel jsem, že se jedná o neočekávanou chybu, která je například způsobenou hardwarem či softwarem. Děkuju
