### ISSUE TITLE
Za jakých okolností nastává chyba RuntimeError?

### ISSUE THREAD

**Issue by xtompok** [nekola03/du3#14]
Měly by se ošetřovat ty chyby, o kterých programátor ví, kdy mohou nastat. Stalo se Ti, že někdy načítání spadlo na `RuntimeError` a v jakém případě?

**Comment by nekola03** [comment]
Dávám pryč. Co jsem pochopil, nastala by v případě pádu softwaru či hardwaru, způsobeného načítáním souboru? Je to asi blbost u takhle "malých" dat.
