### ISSUE TITLE
Maximální vzdálenost adresy od kontejneru lépe definovat jako konstantu

### ISSUE THREAD

**Issue by xtompok** [nekola03/du3#17]
Eliminuje se tím *magická konstanta* v kódu (viz stránky cvičení) a kdyby se v zadání tato vzdálenost změnila, tak stačí upravit tuto konstantu.

**Comment by nekola03** [comment]
Snad to mám. Myslíš definování maximální vzdálenosti jako "PERMISSIBLE_DIS = 10000" viď?

**Comment by xtompok** [comment]
A taky `if (PERMISSIBLE_DIS >= 10000): #v případě vzdálenosti ke kontejneru větší než 10 km, program skončí`, tam to zatím opravené není

**Comment by nekola03** [comment]
Tak jsem to nakonec udělal tak, že jsem PERMISSIBLE_DIS uložil do jiné proměnné minValue pro práci ve funkci. Při změně hodnoty PERMISSIBLE_DIS už bude vše fungovat
