### ISSUE TITLE
Pokud se používají kontejnery s JTSK souřadnicemi, proměnná by se neměla jmenovat `wgs`

### ISSUE THREAD

**Issue by xtompok** [nekola03/du3#4]

**Comment by nekola03** [comment]
Doufám, že jsem pochopil správně, že prostě wgs není vhodný název obecně a je lipší napsat třeba wgsCO(jako coordinates)?

**Comment by xtompok** [comment]
problém je v tom WGS - to je zkratka pro World Geodetic System, 84 je pak rok, od kdy se používá. Pokud jsou souřadnice v S-JTSK, tak zcela jistě nejsou ve WGS84, takže by proměnná, co je drží, neměla mít ve jméně wgs. Vhodné alternativy jsou `coords` nebo `jtsk`.
