### ISSUE TITLE
Maximální vzdálenost lépe definovat jako konstantu na začátku programu

### ISSUE THREAD

**Issue by xtompok** [nekola03/du3#6]

**Comment by nekola03** [comment]
Předpokládám, že se jedná asi o část kódu maximDistance = max(distances.values()). Jenom si nejsem jistý, jak použít na začátku programu. Prozatím jsem použil v sekci v hlavní části programu po získání všech vzdáleností. Je to tedy mimo funkci a funkce vrací jenom 1 proměnnou

**Comment by xtompok** [comment]
Problém je v tom, že se tam uprostřed kódu vyskytuje konstanta 10000, lepší by bylo mít na začátku programu definovanou konstantu např. MAX_DISTANCE=10000. Protože když by pak někdo řekl, že to má být kilometr a ne deset, tak je ihned jasné, kde to změnit.
